### ISSUE TITLE
how can i find config.env in this project?

### ISSUE THREAD

**Issue by rohanarihant** [GraphicDesignElite/forum-app#1]
this is important for importing database.
how can i find config.

**Comment by GraphicDesignElite** [comment]
Hi,
You'll want to create your own config.env file at the root of your project, and add two variables to it
SERVER=development
DB_URI=mongodb://localhost/forum_02 or your local mongo install.

I apologize for the poor documentation as the project is in an early stage.

**Comment by GraphicDesignElite** [comment]
Sorry, one additional item you need to be aware of. Once you get the app running, it will appear completely empty, you will need to create an account inside your app by clicking sign up as you would on any site.  After that, open mongo.exe and do a manual change on your user account, (update) change your userrole value to 'Admin' . This will allow you to add categories and simulate the final app in working form. By default users are added only with userroles and cannot modify categories.

**Comment by rohanarihant** [comment]
Thanks...
you did a great job...
i made change in user role to Admin by default in User Schema to make an admin account for one time
and give database connectivity in app.js it's working fine.....

**Comment by GraphicDesignElite** [comment]
Thank you for pointing out these issues. I will update with a fix so the first account creation defaults to admin.
